# Generated by Django 5.2.8 on 2025-11-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='tegs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
