# Generated by Django 5.2.8 on 2025-11-14 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_algorithm_code_algorithm_tegs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Алгоритм', 'verbose_name_plural': 'Алгоритмы'},
        ),
        migrations.AddField(
            model_name='algorithm',
            name='author_name',
            field=models.CharField(default='Аноним', max_length=150, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(),
        ),
    ]
