# Generated by Django 5.2.8 on 2025-11-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_alter_algorithm_options_algorithm_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='author_name',
            field=models.CharField(max_length=150, verbose_name='Автор'),
        ),
    ]
