# Generated by Django 5.2.8 on 2025-11-18 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_algorithm_moderated_at_algorithm_moderated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='code',
            field=models.TextField(default='', verbose_name='Код алгоритма'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='tegs',
            field=models.TextField(default='', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='algorithm',
            index=models.Index(fields=['status', 'created_at'], name='algorithms__status_e2ed15_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithm',
            index=models.Index(fields=['author_name'], name='algorithms__author__1cd614_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithm',
            index=models.Index(fields=['status'], name='algorithms__status_9941b7_idx'),
        ),
    ]
